version: '3'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    environment:
      DB_MYSQL_HOST: "${WORDPRESS_DB_HOST}"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "${WORDPRESS_DB_USER}"
      DB_MYSQL_PASSWORD: "${WORDPRESS_DB_PASSWORD}"
      DB_MYSQL_NAME: "${WORDPRESS_DB_NAME}"
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
  db:
    image: 'jc21/mariadb-aria:latest'
    environment:
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    volumes:
      - ./data/mysql:/var/lib/mysql